### PR TITLE
Add layoutReload for when switching layouts in sArena, to make awaren…

### PR DESCRIPTION
**Pull request by devai42coding**
Add layoutReload for when switching layouts in sArena, to make sure textures are reloaded correctly, since switching layouts will cause texture issues.

Added a prompt that will ask the user to reload when switching layout due to known issue with textures upon switching layout:
image

### CODE REVIEW

**Comment by Sammers21** [comment]
@devai42coding but why switching layout previously was not causing any issue and was working fine without a reload?

**Comment by devai42coding** [comment]
@Sammers21 They changed something with the texturePools in 11.0 that is causing it. It is no longer being released like previously it could look like, not sure why exactly.

**Comment by Sammers21** [comment]
@devai42coding okay, lets merge it.

**Comment by Sammers21** [comment]
@devai42coding can you also put a question mark to the end. So it would end with 'Reload now to avoid issues?'

**Pull request merged**
