### PR TITLE
Modify deprecated API functions for TWW 11.0

### PR DESCRIPTION
**Pull request by devai42coding**
WIP:
SArena can be opened on TWW beta with these changes, but the functionallity in Arena has not been tested

### CODE REVIEW

**Comment by devai42coding** [comment]
Closing this PR - Will send another one when I get to test the changes on Beta.

**Comment by Sammers21** [comment]
@devai42coding looking forward for your PR

**Comment by devai42coding** [comment]
@Sammers21 Can you create a TWW branch from master? I will create a PR for that branch later tonight then, since I have managed to get it to work fully on TWW beta, but don’t know if it will work on 10.x.x versions. There is one minor bug with the new version I created, but it will be described and only occurs when switching sarena profiles, then you have to reload

**Comment by Sammers21** [comment]
@devai42coding ye sure. I'm not getting notifications on github, can you message me on Telegram(@sammers21) or Discord(sammersx) for faster communications?

**Comment by Sammers21** [comment]
@devai42coding the branch is here: https://github.com/Sammers21/sArena_Updated2_by_sammers/tree/tww_11_0

**Pull request closed without merging**
