### PR TITLE
Absorb graphic changes

### PR DESCRIPTION
**Pull request by devai42coding**
Absorb graphic changes adding overlay on texture

### CODE REVIEW

**Comment by Sammers21** [comment]
@devai42coding thank you for the Pull Request. Can you please change the base branch to master?

**Comment by Sammers21** [comment]
@devai42coding with that change absorbs are looking a way better. But the texture is looking more dark than it should be.
How it looks:
image

How it should look(on the rogue):
image

**Comment by devai42coding** [comment]
This is a lot brighter I would say:
image

**Comment by devai42coding** [comment]
Updated PR with the above changes

**Comment by devai42coding** [comment]
Updated PR with the above changes

**Comment by Sammers21** [comment]
@devai42coding ok i will test it. Thank you

**Comment by Sammers21** [comment]
@devai42coding that looks better, but still i feel like its a bit dark or shady comparting to the absorbs on blizzard frames

image

**Comment by Sammers21** [comment]
I will merge it and release a new version @devai42coding. Thank you for the contribution. But if you feel like you can make it look closer to the original absorbs on blizzard frames feel free to make another PR

**Comment by devai42coding** [comment]
> @devai42coding that looks better, but still i feel like its a bit dark or shady comparting to the absorbs on blizzard frames
> 
> image

I suspect it is addon skin related. this is how it looks like for me:
image

So not sure why it shows darker on yours with newest commit.

**Pull request merged**
